on:
  workflow_call:
jobs:
  cypress-test:
    name: Cypress tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          TZ: Europe/Copenhagen
        with:
          working-directory: ./web
          start: yarn develop
          wait-on: 'http://localhost:8080'
