on:
  workflow_call:

jobs:
  jest-test:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'yarn'
          cache-dependency-path: web/yarn.lock
      - name: Install
        run: yarn install --frozen-lockfile
        working-directory: ./web
      - name: Run test
        run: yarn run test
        working-directory: ./web
