steps:
  prepare:
    image: node:16.15
    inputs:
      - package.json
      - yarn.lock
    commands:
      - yarn

  build:
    environment:
      ELECTRICITYMAP_PUBLIC_TOKEN: ${BRICK_ELECTRICITYMAP_PUBLIC_TOKEN:-unknown}
      COMMIT_SHA: ${BRICK_DRONE_COMMIT_SHA:-unknown}
    inputs:
      # geometries
      - geo
      # source code
      - ../config/{exchanges,zones}.json
      - ./{locales-config.json,translation-status.js}
      - public/{fonts,images,locales,apple-app-site-association,browserconfig.xml,electricityMap.webmanifest,client-version.json}
      - src
      - views
      - ./{.babelrc,.eslintrc.js,server.js,webpack.config.js}
    commands:
      - mkdir -p public/dist
      - yarn update-version
      - yarn build-release
    outputs:
      - src/world.json
      - public/dist
    tag: eu.gcr.io/tmrow-152415/electricitymap_web

  deploy:
    image: google/cloud-sdk:243.0.0
    commands:
      - gsutil -m cp -a public-read -r public/* gs://static.electricitymap.org/public_web
      - gsutil setmeta -h "Cache-Control:no-cache,max-age=0" gs://static.electricitymap.org/public_web/client-version.json
      - gsutil setmeta -h "Cache-Control:no-cache,max-age=0" gs://static.electricitymap.org/public_web/dist/manifest.json
    secrets:
      gcloud:
        src: ~/.config/gcloud
        target: /root/.config/gcloud
